name:                pr-notifier
version:             0.1.0.0
github:              "narley/pr-notifier"
license:             BSD3
author:              "Narley Brittes"
maintainer:          "n@brittes.co.uk"
copyright:           "2020 Narley Brittes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/narley/pr-notifier#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- rio
- wreq
- lens
- process
- text
- haskeline
- directory
- split
- utf8-string

library:
  source-dirs: src

executables:
  pr-notifier:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pr-notifier

tests:
  pr-notifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pr-notifier
